"use client";

import { FormProvider } from "../components/FormContext";
// import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };





import { headers } from 'next/headers';
import { redirect } from 'next/navigation';

import { auth } from '_helpers/server';
import { Alert, NavB,Sidebar } from '_components';
export default Layout;

function Layout({ children }: { children: React.ReactNode }) {

    return (
        <div>
              <div >
        <FormProvider>{children}</FormProvider>
    </div>
        </div>

    );
}

