"use client";

import { FormProvider } from "../components/FormContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div >
        <FormProvider>{children}</FormProvider>
    </div>
  );
}
